AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Create a basic EC2 instance for general uc.
  Type OS : CentOS
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: 'AWS::EC2::KeyPair::KeyName'
    Default: {{ KeyName }}
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  MasterInstanceType:
    Description: Master EC2 instance type
    Type: String
    Default: t2.nano
    AllowedValues:
      - t2.nano
      - t2.micro     
Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-01ed306a12b7d1c96
    us-east-2:
      AMI: ami-01ed306a12b7d1c96
    us-west-1:
      AMI: ami-01ed306a12b7d1c96
    us-west-2:
      AMI: ami-01ed306a12b7d1c96
Resources:
  AbafarVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.201.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: AbafarVPC  
  LabInternetGateway:
    Type: AWS::EC2::InternetGateway
  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
        VpcId: !Ref AbafarVPC
        InternetGatewayId: !Ref LabInternetGateway
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref AbafarVPC
      CidrBlock: 10.201.10.0/24
      MapPublicIpOnLaunch: true
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref AbafarVPC
  InternetRoute:
    Type: AWS::EC2::Route
    DependsOn: LabInternetGateway
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref LabInternetGateway
      RouteTableId: !Ref PublicRouteTable
  SubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet1
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: 'Internet Group'
      GroupDescription: "SSH traffic in, all traffic out."
      VpcId: !Ref AbafarVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
  MasterEC2:
    Type: AWS::EC2::Instance 
    Properties:
      ImageId: !FindInMap
        - RegionMap
        - !Ref 'AWS::Region'
        - AMI
      SecurityGroupIds:
        - !Ref SSHSecurityGroup     
      InstanceType: !Ref MasterInstanceType
      KeyName: !Ref KeyName
      SubnetId: !Ref PublicSubnet1
      BlockDeviceMappings:
      - DeviceName: /dev/sda1
        Ebs:
          VolumeType: gp2
          DeleteOnTermination: true
          VolumeSize: 8
      PrivateIpAddress: 10.201.10.90
      Tags:
        - Key: Name
          Value: abafarEC2
        - Key: ClusterName
          Value: abafar