- name: Install init script
  copy: src=create_stack.sh dest=/tmp mode=0755

- name: Copy stack EC2 in temp folder
  template: src=ec2.yml dest=/tmp/

- name: Create stack
  command: /tmp/create_stack.sh
